package test.folder;

import java.awt.Choice;
import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import test.folder.*;
import java.util.Random;
import javax.swing.JFrame;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private text textran;
    private String randomtext;
    private Choice PhotoAdd;
    private int textindex,indexPhoto,numberphoto;
    private photo photoran;
    private long butm_1,butm1,frist,kk,k2,k11,k3,k13,k7,k12,k8,k6,hh2,hh11,hh3,hh13,hh7,hh12,hh8,hh6;
    
    public NewJFrame() {
        indexPhoto=0;
        PhotoAdd=new Choice();
        textran=new text();
        photoran=new photo();
        photoran.type(gett());
         //System.out.println(gg[1]);
        initComponents();
    }
    
    /**

     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jText = new javax.swing.JTextField();
        jButtonReset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton_1 = new javax.swing.JButton();
        jButton_6 = new javax.swing.JButton();
        jButton_5 = new javax.swing.JButton();
        jButton_10 = new javax.swing.JButton();
        jButton_2 = new javax.swing.JButton();
        jButton_7 = new javax.swing.JButton();
        jButton_3 = new javax.swing.JButton();
        jButton_4 = new javax.swing.JButton();
        jButton_9 = new javax.swing.JButton();
        jButton_8 = new javax.swing.JButton();
        jButtoncheck = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setForeground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jLabel1.setText("Recaptcha");

        jText.setFont(new java.awt.Font("Angsana New", 0, 36)); // NOI18N
        jText.setText(textrandom());
        jText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextActionPerformed(evt);
            }
        });

        jButtonReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/folder/1.jpg"))); // NOI18N
        jButtonReset.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jButtonResetComponentAdded(evt);
            }
        });
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(454, 454, 454))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jText))
                .addGap(22, 22, 22))
        );

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jButton_1.setIcon(new javax.swing.ImageIcon(asd()));
        jButton_1.setIconTextGap(numberphoto);
        jButton_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_1ActionPerformed(evt);
            }
        });

        jButton_6.setIcon(new javax.swing.ImageIcon(asd()));
        jButton_6.setIconTextGap(numberphoto);
        jButton_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_6ActionPerformed(evt);
            }
        });

        jButton_5.setIcon(new javax.swing.ImageIcon(asd()));
        jButton_5.setIconTextGap(numberphoto);
        jButton_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_5ActionPerformed(evt);
            }
        });

        jButton_10.setIcon(new javax.swing.ImageIcon(asd()));
        jButton_10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_10.setIconTextGap(numberphoto);
        jButton_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_10ActionPerformed(evt);
            }
        });

        jButton_2.setIcon(new javax.swing.ImageIcon(asd()));
        jButton_2.setIconTextGap(numberphoto);
        jButton_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_2ActionPerformed(evt);
            }
        });

        jButton_7.setIcon(new javax.swing.ImageIcon(asd()));
        jButton_7.setIconTextGap(numberphoto);
        jButton_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_7ActionPerformed(evt);
            }
        });

        jButton_3.setBackground(new java.awt.Color(255, 255, 255));
        jButton_3.setForeground(new java.awt.Color(240, 240, 240));
        jButton_3.setIcon(new javax.swing.ImageIcon(asd()));
        jButton_3.setIconTextGap(numberphoto);
        jButton_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_3ActionPerformed(evt);
            }
        });

        jButton_4.setIcon(new javax.swing.ImageIcon(asd()));
        jButton_4.setIconTextGap(numberphoto);
        jButton_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_4ActionPerformed(evt);
            }
        });

        jButton_9.setIcon(new javax.swing.ImageIcon(asd()));
        jButton_9.setIconTextGap(numberphoto);
        jButton_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_9ActionPerformed(evt);
            }
        });

        jButton_8.setIcon(new javax.swing.ImageIcon(asd()));
        jButton_8.setIconTextGap(numberphoto);
        jButton_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_8ActionPerformed(evt);
            }
        });

        jButtoncheck.setBackground(new java.awt.Color(102, 255, 102));
        jButtoncheck.setText("ตรวจคำตอบ");
        jButtoncheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncheckActionPerformed(evt);
            }
        });

        jButtonExit.setBackground(new java.awt.Color(0, 51, 255));
        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_6, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_7, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_8, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_9, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_5, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_10, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(jButtoncheck, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(435, 435, 435))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton_2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtoncheck, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(79, 79, 79)
                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_1ActionPerformed
 if(butm1==butm_1){
            butm_1=evt.getWhen();
            jButton_1.setBackground(Color.blue);
            //System.out.println(jButton_1.getIconTextGap()+"check");
    PhotoAdd.addItem(String.valueOf(jButton_1.getIconTextGap()));
        indexPhoto++;
    System.out.println(indexPhoto);
}else{
            butm1=butm_1;
            jButton_1.setBackground(Color.white);
            PhotoAdd.remove(String.valueOf(jButton_1.getIconTextGap()));
indexPhoto--;
System.out.println(indexPhoto);
    

}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton_1ActionPerformed

    private void jButton_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_5ActionPerformed
     if(k3==hh3){
            hh3=evt.getWhen();
            jButton_5.setBackground(Color.BLUE);
            //System.out.println(jButton_5.getIconTextGap()+"check");
    PhotoAdd.addItem(String.valueOf(jButton_5.getIconTextGap()));
        indexPhoto++;
    System.out.println(indexPhoto);
    
}else{
            k3=hh3;
            jButton_5.setBackground(Color.white);
    PhotoAdd.remove(String.valueOf(jButton_5.getIconTextGap()));
indexPhoto--;
System.out.println(indexPhoto);  
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_5ActionPerformed
    }
    private void jButton_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_3ActionPerformed

        if(k2==hh2){
            hh2=evt.getWhen();
            jButton_3.setBackground(Color.BLUE);
            //System.out.println(jButton_3.getIconTextGap()+"check");
    PhotoAdd.addItem(String.valueOf(jButton_3.getIconTextGap()));
        indexPhoto++;

    System.out.println(indexPhoto);
    
}else{
            k2=hh2;
            jButton_3.setBackground(Color.white);
    PhotoAdd.remove(String.valueOf(jButton_3.getIconTextGap()));
indexPhoto--;
System.out.println(indexPhoto);
    

}     // TODO add your handling code here: 
    }//GEN-LAST:event_jButton_3ActionPerformed

    private void jButton_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_10ActionPerformed
    if(k6==hh6){
            hh6=evt.getWhen();
            jButton_10.setBackground(Color.BLUE);
            //System.out.println(jButton_10.getIconTextGap()+"check");
    PhotoAdd.addItem(String.valueOf(jButton_10.getIconTextGap()));
        indexPhoto++;
    System.out.println(indexPhoto);
    
}else{
            k6=hh6;
            jButton_10.setBackground(Color.white);
    PhotoAdd.remove(String.valueOf(jButton_10.getIconTextGap()));
indexPhoto--;
System.out.println(indexPhoto);}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_10ActionPerformed

    private void jButton_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_7ActionPerformed
if(k7==hh7){
            hh7=evt.getWhen();
            jButton_7.setBackground(Color.BLUE);
            //System.out.println(jButton_7.getIconTextGap()+"check");
    PhotoAdd.addItem(String.valueOf(jButton_7.getIconTextGap()));
        indexPhoto++;
    System.out.println(indexPhoto);
    
}else{
            k7=hh7;
            jButton_7.setBackground(Color.WHITE);
    PhotoAdd.remove(String.valueOf(jButton_7.getIconTextGap()));
indexPhoto--;
System.out.println(indexPhoto); }       // TODO add your handling code here:
    }//GEN-LAST:event_jButton_7ActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
restart();
           // TODO add your handling code here:
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtoncheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncheckActionPerformed
boolean che=true;
int k=0;
if(PhotoAdd.getItemCount()<5|PhotoAdd.getItemCount()>5){
    che=false;
}else{
while(k<PhotoAdd.getItemCount()&che==true){
if(Integer.valueOf(PhotoAdd.getItem(k))<5){
    k++;
}else{
    che=false;
}
}
}
if(che==true){
    jPanel3.setBackground(Color.GREEN);
    JOptionPane.showMessageDialog(null, "You are not bot");
    JFrame3 ne=new JFrame3();
    ne.setVisible(true);
    ne.show();  
}else{
    jPanel3.setBackground(Color.red);
    JOptionPane.showMessageDialog(null, "You are bot");
    JFrame2 j=new JFrame2();
    j.setVisible(true);
    j.show();
    this.setVisible(false);
}
  // TODO add your handling code here:
    }//GEN-LAST:event_jButtoncheckActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextActionPerformed

    private void jButton_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_6ActionPerformed
if(k13==hh13){
            hh13=evt.getWhen();
            jButton_6.setBackground(Color.BLUE);
            System.out.println(jButton_6.getIconTextGap()+"check");
    PhotoAdd.addItem(String.valueOf(jButton_6.getIconTextGap()));
        indexPhoto++;
    System.out.println(indexPhoto);
    
}else{
            k13=hh13;
            jButton_6.setBackground(Color.WHITE);
    PhotoAdd.remove(String.valueOf(jButton_6.getIconTextGap()));
indexPhoto--;
System.out.println(indexPhoto);}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_6ActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
jFrame1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
System.exit(WIDTH);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButton_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_2ActionPerformed

        if(frist==kk){
            kk=evt.getWhen();
            jButton_2.setBackground(Color.BLUE);
            System.out.println(jButton_2.getIconTextGap()+"check");
    PhotoAdd.addItem(String.valueOf(jButton_2.getIconTextGap()));
        indexPhoto++;
    System.out.println(indexPhoto);
    
}else{
            frist=kk;
            jButton_2.setBackground(Color.WHITE);
    PhotoAdd.remove(String.valueOf(jButton_2.getIconTextGap()));
indexPhoto--;
System.out.println(indexPhoto);
    

} // TODO add your handling code here:
    }//GEN-LAST:event_jButton_2ActionPerformed

    private void jButtonResetComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jButtonResetComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonResetComponentAdded

    private void jButton_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_9ActionPerformed
 if(k8==hh8){
            hh8=evt.getWhen();
            jButton_9.setBackground(Color.BLUE);
            System.out.println(jButton_9.getIconTextGap()+"check");
    PhotoAdd.addItem(String.valueOf(jButton_9.getIconTextGap()));
        indexPhoto++;
    System.out.println(indexPhoto);
    
}else{
            k8=hh8;
            jButton_9.setBackground(Color.WHITE);
    PhotoAdd.remove(String.valueOf(jButton_9.getIconTextGap()));
indexPhoto--;
System.out.println(indexPhoto);
        // TODO add your handling code here:
    }      // TODO add your handling code here:
    }//GEN-LAST:event_jButton_9ActionPerformed

    private void jButton_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_4ActionPerformed
if(k11==hh11){
            hh11=evt.getWhen();
            jButton_4.setBackground(Color.BLUE);
            System.out.println(jButton_4.getIconTextGap()+"check");
    PhotoAdd.addItem(String.valueOf(jButton_4.getIconTextGap()));
        indexPhoto++;
    
    System.out.println(indexPhoto);
    
}else{
            k11=hh11;
            jButton_4.setBackground(Color.WHITE);
    PhotoAdd.remove(String.valueOf(jButton_4.getIconTextGap()));
indexPhoto--;
System.out.println(indexPhoto);
        // TODO add your handling code here:
    } 
  // TODO add your handling code here:
    }//GEN-LAST:event_jButton_4ActionPerformed

    private void jButton_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_8ActionPerformed
if(k12==hh12){
            hh12=evt.getWhen();
            jButton_8.setBackground(Color.BLUE);
            System.out.println(jButton_8.getIconTextGap()+"check");
    PhotoAdd.addItem(String.valueOf(jButton_8.getIconTextGap()));
        indexPhoto++;
    System.out.println(indexPhoto);
    
}else{
            k12=hh12;
            jButton_8.setBackground(Color.WHITE);
    PhotoAdd.remove(String.valueOf(jButton_8.getIconTextGap()));
indexPhoto--;
System.out.println(indexPhoto);
        // TODO add your handling code here:
    }       // TODO add your handling code here:
    }//GEN-LAST:event_jButton_8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public String textrandom(){
        String p=textran.gettext();
        return p;
    }
    public String asd(){
        randomtext=photoran.randomphoto();
        numberphoto=photoran.getrandom();
        //System.out.println(u.getrandom());
        return randomtext;
    }
    public int gett(){
        textindex=textran.textindex();
        //System.out.println(t);//textrandom();
        return textindex;
    }
    public void restart(){
        indexPhoto=0;
        PhotoAdd=new Choice();
        textran=new text();
        photoran=new photo();
        photoran.type(gett());
        jText.setText(textrandom());
        butm_1=butm1;frist=kk;k2=hh2;k11=hh11;k3=hh3;k13=hh13;k7=hh7;k12=hh12;k8=hh8;k6=hh6;
jButton_1.setIcon(new javax.swing.ImageIcon(asd()));jButton_1.setIconTextGap(numberphoto);jButton_1.setBackground(Color.white);
jButton_2.setIcon(new javax.swing.ImageIcon(asd()));jButton_2.setIconTextGap(numberphoto);jButton_2.setBackground(Color.white);
jButton_3.setIcon(new javax.swing.ImageIcon(asd()));jButton_3.setIconTextGap(numberphoto);jButton_3.setBackground(Color.white);
jButton_4.setIcon(new javax.swing.ImageIcon(asd()));jButton_4.setIconTextGap(numberphoto);jButton_4.setBackground(Color.white);
jButton_5.setIcon(new javax.swing.ImageIcon(asd()));jButton_5.setIconTextGap(numberphoto);jButton_5.setBackground(Color.white);
jButton_6.setIcon(new javax.swing.ImageIcon(asd()));jButton_6.setIconTextGap(numberphoto);jButton_6.setBackground(Color.white);
jButton_7.setIcon(new javax.swing.ImageIcon(asd()));jButton_7.setIconTextGap(numberphoto);jButton_7.setBackground(Color.white);
jButton_8.setIcon(new javax.swing.ImageIcon(asd()));jButton_8.setIconTextGap(numberphoto);jButton_8.setBackground(Color.white);
jButton_9.setIcon(new javax.swing.ImageIcon(asd()));jButton_9.setIconTextGap(numberphoto);jButton_9.setBackground(Color.white);
jButton_10.setIcon(new javax.swing.ImageIcon(asd()));jButton_10.setIconTextGap(numberphoto);jButton_10.setBackground(Color.white);
jPanel3.setBackground(Color.white);
    }
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 new NewJFrame().setVisible(true);    
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButton_1;
    private javax.swing.JButton jButton_10;
    private javax.swing.JButton jButton_2;
    private javax.swing.JButton jButton_3;
    private javax.swing.JButton jButton_4;
    private javax.swing.JButton jButton_5;
    private javax.swing.JButton jButton_6;
    private javax.swing.JButton jButton_7;
    private javax.swing.JButton jButton_8;
    private javax.swing.JButton jButton_9;
    private javax.swing.JButton jButtoncheck;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jText;
    // End of variables declaration//GEN-END:variables
}
